export enum EnumRoles {
  NedaadadasaaadminedaadadAsaaadminedaadadasaaadminedaadadasaaadminedaadadasaaadminedaadadasaaadminedaadadasaaadminedaadadasaanedaadadasAaadminedaadadasaaadminedaadadasaaadminedaadadasaaadminedaadadasaaadminedaadadasaaadminedaadadasaaadminedaadadasaanedaadadasaaadminedaadadasaaadminedaadadasaaadminedaadadasaaadminedaadadasaaadminedaadadasaaadminedaadadasaaadminedaadadasaa = "leadSeniorPrimaryManagerOfUnit_1",
  User = "user",
  LeadSeniorPrimaryManagerUnitWashingtonDcUsa = "nedaadadasaaadminedaadadasaaadminedaadadasaaadminedaadadasaaadminedaadadasaaadminedaadadasaaadminedaadadasaaadminedaadadasaa",
}
